openapi: 3.1.0
info:
  version: 1.0.0
  title: Task Pro app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of Task Pro app.
tags:
  - name: Auth
    description: Auth operations.
  - name: Users
    description: User profile and settings operations.
  - name: Boards
    description: Operations for managing boards.
  - name: Columns
    description: Operations for managing columns.
  - name: Cards
    description: Operations for managing tasks.
  - name: Help
    description: Possibility of sending a letter with a comment about help to the address - Taskpro.project@gmail.com
servers:
  - url: http://127.0.0.1:3000
  - url: https://pr5-ltp-rn-back.onrender.com
paths:
  /auth/register:
    post:
      $ref: ../swagger/paths/auth/register.yaml
  /auth/login:
    post:
      $ref: ../swagger/paths/auth/login.yaml
  /auth/logout:
    post:
      $ref: ../swagger/paths/auth/logout.yaml
  /users/current:
    get:
      $ref: ../swagger/paths/users/current.yaml
  /users/info:
    patch:
      $ref: ../swagger/paths/users/info.yaml
  /users/theme:
    patch:
      $ref: ../swagger/paths/users/theme.yaml
  /boards:
    post:
      $ref: ../swagger/paths/boards/post.yaml
    get:
      $ref: ../swagger/paths/boards/get.yaml
  /boards/{id}:
    get:
      $ref: ../swagger/paths/boards/{id}/get.yaml
    patch:
      $ref: ../swagger/paths/boards/patch.yaml
    delete:
      $ref: ../swagger/paths/boards/delete.yaml
  /columns:
    post:
      $ref: ../swagger/paths/columns/post.yaml
    get:
      $ref: ../swagger/paths/columns/get.yaml
  /columns/{id}:
    patch:
      $ref: ../swagger/paths/columns/patch.yaml
    delete:
      $ref: ../swagger/paths/columns/delete.yaml
  /cards:
    post:
      $ref: ../swagger/paths/cards/post.yaml
  /cards/{id}:
    patch:
      $ref: ../swagger/paths/cards/patch.yaml
    delete:
      $ref: ../swagger/paths/cards/delete.yaml
  /help:
    post:
      $ref: ../swagger/paths/help/post.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
