openapi: 3.1.0
info:
  version: 1.0.0
  title: Task Pro app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of Task Pro app.
tags:
  - name: Auth
    description: Auth operations.
  - name: User
    description: User profile and settings operations.
  - name: Boards
    description: Operations for managing boards, columns, and cards.
  # - name: Theme
  #   description: Operations for changing and saving user theme settings.
servers:
  - url: http://127.0.0.1:3000
  - url: https://pr5-ltp-rn-back.onrender.com
paths:
  /auth/register:
    post:
      $ref: ../swagger/paths/auth/register.yaml
  /auth/login:
    post:
      $ref: ../swagger/paths/auth/login.yaml
  /auth/logout:
    post:
      $ref: ../swagger/paths/auth/logout.yaml
  /users/current:
    get:
      $ref: ../swagger/paths/users/current.yaml
  /users/{userId}:
    patch:
      $ref: ../swagger/paths/users/update.yaml
  /users/themes:
    patch:
      $ref: ../swagger/paths/users/themes.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
